# Generated by Django 6.0.2 on 2026-02-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Valentine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipient_name", models.CharField(max_length=100)),
                ("sender_name", models.CharField(max_length=100)),
                ("message", models.TextField()),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("classic", "Classic Rose"),
                            ("midnight", "Midnight Soul"),
                            ("golden", "Golden Love"),
                        ],
                        default="classic",
                        max_length=20,
                    ),
                ),
                ("music_link", models.URLField(blank=True, null=True)),
                ("image_url", models.URLField(blank=True, null=True)),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
                ("is_accepted", models.BooleanField(default=False)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("views_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["slug"], name="valentines__slug_179ba7_idx"),
                    models.Index(
                        fields=["-created_at"], name="valentines__created_584b75_idx"
                    ),
                ],
            },
        ),
    ]
