# Generated by Django 6.0.2 on 2026-02-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("valentines", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="valentine",
            name="template_type",
            field=models.CharField(
                choices=[
                    ("classic", "Classic Gift Box"),
                    ("love_letter", "Love Letter (Premium)"),
                ],
                default="classic",
                max_length=20,
            ),
        ),
    ]
