# Generated by Django 6.0.2 on 2026-02-13 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("valentines", "0002_valentine_template_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="valentine",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Optional title for Poems or Letters",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="valentine",
            name="template_type",
            field=models.CharField(
                choices=[
                    ("classic", "Classic Gift Box"),
                    ("love_letter", "Love Letter (Premium)"),
                    ("poem", "Romantic Poem (Premium)"),
                ],
                default="classic",
                max_length=20,
            ),
        ),
    ]
