# Generated by Django 6.0 on 2026-02-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("valentines", "0003_valentine_title_alter_valentine_template_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="valentine",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="valentines/"),
        ),
    ]
