# Generated by Django 6.0 on 2026-02-13 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("valentines", "0004_valentine_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="valentine",
            name="is_premium_tracking",
            field=models.BooleanField(
                default=False, help_text="Paid to bypass notification rules"
            ),
        ),
        migrations.AddField(
            model_name="valentine",
            name="management_token",
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name="valentine",
            name="protection_answer",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="valentine",
            name="protection_question",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name="valentine",
            index=models.Index(
                fields=["management_token"], name="valentines__managem_3f4be2_idx"
            ),
        ),
    ]
