# Generated by Django 6.0 on 2026-02-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("valentines", "0005_valentine_is_premium_tracking_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="valentine",
            name="sender_location",
            field=models.CharField(
                blank=True, help_text="e.g. Nairobi, Kenya", max_length=100, null=True
            ),
        ),
    ]
