# Generated by Django 6.0 on 2026-02-13 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("valentines", "0006_valentine_sender_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="valentine",
            name="amount_paid",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="valentine",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="valentine",
            name="paystack_ref",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
