# Generated by Django 6.0 on 2026-02-13 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("valentines", "0007_valentine_amount_paid_valentine_is_paid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="valentine",
            name="mpesa_checkout_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="valentine",
            name="mpesa_phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
