# Generated by Django 6.0 on 2026-02-13 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("valentines", "0008_valentine_mpesa_checkout_id_valentine_mpesa_phone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="valentine",
            name="mpesa_checkout_id",
        ),
        migrations.RemoveField(
            model_name="valentine",
            name="paystack_ref",
        ),
        migrations.AddField(
            model_name="valentine",
            name="is_pending_verification",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="valentine",
            name="mpesa_code",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
